{% set name="apache-tvm-ffi" %}
{% set version="0.1.9" %}
{% set dlpack_ext_version="0.1.9" %}
{% set build_num=0 %}

package:
  name: apache-tvm-ffi-packages
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: d2d402587e8906de0a07f4746aa78f3d452c7efe3625d4bb39ac2ad693bce530


outputs:
  - name: {{ name }}
    build:
      number: {{ build_num }}
      skip: true # [win]
      script:
        - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
        #- {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
        - $PYTHON -m pip install . -vv --no-deps --no-build-isolation
      version: {{ version }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - ninja
        - make
        - scikit-build-core >=0.10.0
        - setuptools-scm
        - cython >=3.0
        - wheel
        - pip
      host:
        - python
        - pip
        - scikit-build-core >=0.10.0
        - cython >=3.0
        - setuptools
        - setuptools-scm
      run:
        - python
        - typing-extensions >=4.5

    test:
      imports:
            - tvm_ffi
      requires:
        - pip
      commands:
        - pip check
  - name: torch-c-dlpack-ext
    build: 
      number: {{ build_num }}
      skip: true # [win]
      version: {{ dlpack_ext_version }}
      script: 
        - cd addons/torch_c_dlpack_ext
        - pwd
        - $PYTHON -m pip install . -vv --no-deps --no-build-isolation
        - pwd
        - exit 1
    requirements:
      build:
      host:
        - {{ pin_subpackage(name, exact=True) }}
        - pytorch
        - python
        - pip
        - wheel
        - setuptools >=61.0
      run:
    test:
      imports:
        - torch_c_dlpack_ext
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://github.com/apache/tvm-ffi
  summary: TVM FFI - Foreign Function Interface for ML systems
  description: |
    TVM FFI is a lightweight foreign function interface library designed for
    machine learning systems. It provides efficient cross-language bindings
    between Python and C++.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/apache/tvm-ffi
  doc_url: https://tvm.apache.org/ffi/


extra:
  recipe-maintainers:
    - iamthebot
